version: '2'

services:
    pimp:
        volumes:
            - ..:/home/pimp/pimp
            - ./media:/home/pimp/media
            - ./frank:/home/pimp/frank
        command: ./start_pimp_dev.sh
        ports:
            - "${EXTERNAL_PORT}:8000"
            - "${JUPYTER_PORT}:8888"
        environment:
            - EXTERNAL_NIST_QUERY_DIR=${PWD}/frank/NISTQueryFiles
    mysql:
        ports:
            - "3306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
