stages:
  - build
  - push

#pimp-base:
#    script:
#        - cd DockerBaseContext
#        - docker-compose build pimp-base
#    stage: build

test-pimp:
    script:
        - 'set | grep -i http'
    stage: build
