stages:
  - build
  - push

variables:
    PROXY_SETTINGS: >
            --build-arg=http_proxy=http://wwwcache.gla.ac.uk:8080/
            --build-arg=HTTP_PROXY=http://wwwcache.gla.ac.uk:8080/
            --build-arg=https_proxy=http://wwwcache.gla.ac.uk:8080/
            --build-arg=HTTPS_PROXY=http://wwwcache.gla.ac.uk:8080/
            --build-arg=NO_PROXY=localhost,127.0.0.1
            --build-arg=no_proxy=localhost,127.0.0.1

pimp-base:
    script:
        - cd DockerBaseContext
        - docker build -t pimp-base
            $PROXY_SETTINGS
            .
    stage: build


.test-pimp:
    script:
        - cd DockerTestContext
        - docker build --no-cache -t test-image
            $PROXY_SETTINGS
            .
    stage: build

#    variables:
#        CI_DEBUG_TRACE: "true"
