stages:
  - build
  - push

#pimp-base:
#    script:
#        - cd DockerBaseContext
#        - docker-compose build pimp-base
#    stage: build

test-pimp:
    script:
        - cd DockerTestContext
        - docker-compose build test
    stage: build
