version: '2'

services:
    pimp:
        image: ${PIMP_IMAGE}
        hostname: pimp
        environment:
            - PIMP_DATABASE_HOST=mysql
            - PYTHONUNBUFFERED=1
            - MYSQL_DATABASE
            - MYSQL_USER
            - MYSQL_PASSWORD
            - PIMP_INITIAL_USERNAME
            - PIMP_INITIAL_EMAIL_ADDRESS
            - PIMP_INITIAL_PASSWORD
            - PIMP_INITIAL_FIRST_NAME
            - PIMP_INITIAL_LAST_NAME
        extends:
            file: common.yml
            service: logging
        volumes:
            - media:/home/pimp/media
            - backups:/home/pimp/backups
    mysql:
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE
            - MYSQL_USER
            - MYSQL_PASSWORD
        image: ${MYSQL_IMAGE}
        hostname: mysql
        extends:
            file: common.yml
            service: logging
        command: mysqld --range_optimizer_max_mem_size=0

volumes:
        media:
        backups:
