version: '2'

services:
    pimp:
        image: ${PIMP_IMAGE}
        build: .
        hostname: pimp
        environment:
            - PIMP_DATABASE_HOST=mysql
            - PYTHONUNBUFFERED=1
            - MYSQL_DATABASE
            - MYSQL_USER
            - MYSQL_PASSWORD
            - PIMP_INITIAL_USERNAME
            - PIMP_INITIAL_EMAIL_ADDRESS
            - PIMP_INITIAL_PASSWORD
            - PIMP_INITIAL_FIRST_NAME
            - PIMP_INITIAL_LAST_NAME
            - PIMP_DEBUG
            - PIMP_LOG_LEVEL
            - MSPEPSEARCH_IMAGE
            - INTERNAL_NIST_QUERY_DIR=/home/pimp/frank/NISTQueryFiles
        extends:
            file: common.yml
            service: logging
        depends_on:
        - mysql
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - .:/home/pimp/backups
    mysql:
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE
            - MYSQL_USER
            - MYSQL_PASSWORD
        image: ${MYSQL_IMAGE}
        hostname: mysql
        extends:
            file: common.yml
            service: logging
        command: mysqld --range_optimizer_max_mem_size=0
        volumes:
            - .:/backups
