version: '2'

services:
    pimp:
        image: ${PIMP_IMAGE}
        container_name: pimp
        hostname: pimp
        environment:
            - PIMP_DATABASE_HOST=mysql
            - PYTHONUNBUFFERED=1
            - MYSQL_DATABASE
            - MYSQL_USER
            - MYSQL_PASSWORD
        depends_on:
            - mysql
        extends:
            file: common.yml
            service: logging
    mysql:
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE
            - MYSQL_USER
            - MYSQL_PASSWORD
        image: ${MYSQL_IMAGE}
        container_name: mysql
        hostname: mysql
        extends:
            file: common.yml
            service: logging
    nginx:
        container_name: nginx
        hostname: nginx
        volumes_from:
            - pimp
        image: ${NGINX_IMAGE}
        environment:
            - PIMP_HOSTNAME=pimp
            - EXTERNAL_HOSTNAME
            - EXTERNAL_HOST_AND_PORT
            - NGINX_ERROR_LOGLEVEL
        command: /bin/bash -c "envsubst < /etc/nginx/conf.d/pimp.conf.template > /etc/nginx/conf.d/pimp.conf && nginx -g 'daemon off;'"
        depends_on:
            - pimp
        ports:
            - "${EXTERNAL_PORT}:80"
        extends:
            file: common.yml
            service: logging
